### ISSUE TITLE
Close on click outside?

### ISSUE THREAD

**Issue by JackEdwardLyons** [accessible-ui/drawer#3]
Hi there,

Is it possible to close the drawer on click outside?

Thanks

**Comment by jaredLunde** [comment]
Not worth building into the library IMO. Can be accomplished easily in user land:
https://github.com/Andarist/use-onclickoutside

```jsx
import {Target, useDrawer} from '@accessible/drawer'

function MyDrawerTarget () {
  const {close} = useDrawer()
  const ref = React.useRef(null)
  useOnClickOutside(ref, close)

  return <Target><div ref={ref}>Drawer content</div></Target>
}
```

**Comment by JackEdwardLyons** [comment]
Hi thanks for the reply - I did exactly this in a code sandbox (https://codesandbox.io/s/accessibledrawer-example-forked-lyquc?file=/src/index.js) and it's not closing on click outside. Any ideas why that might be?

Thanks in advance.

**Comment by jaredLunde** [comment]
`useDrawer()` has to be inside the `<Drawer>` context:
https://codesandbox.io/s/accessibledrawer-example-forked-3vde8?file=/src/index.js
