### ISSUE TITLE
Multiple Triggers on one page

### ISSUE THREAD

**Issue by janhesters** [accessible-ui/drawer#6]
I have two triggers:

```jsx
<Trigger>
  <button>Button 1</button>
</Trigger>

<Trigger>
  <button>Button 2</button>
</Trigger>

<Target
  closedStyle={DrawerTargetStyles}
  openStyle={DrawerTargetStyles}
  placement="right"
>
  <Drawer role="menu">
    <SettingsDrawer onDrawerCloseClick={onDrawerCloseClick} />
  </Drawer>
</Target>
```

Whenever I close the drawer, the focus always goes to button 2, even though Button 1 opened it.

Is there a way to have different buttons opening the drawer and returning to the correct focus?

**Comment by jaredLunde** [comment]
You can just use context for the trigger you don't want focused. The second button will always draw the focus because it's the last rendered in the tree.
