### ISSUE TITLE
Focus Trap

### ISSUE THREAD

**Issue by mckelveygreg** [accessible-ui/drawer#7]
Just found your library! I've been trying up my a11y game lately, so this really excited me.

I'm having an issue however. My tabbing focus continues on the page and does not loop back to the beginning on the `<Target>` when the target is open. Is this intended behavior or do I need to configure something differently?

Here is the snippet I'm working with:
```
<Drawer>
      <Nav isLightText={isLightText}>
        <HomeLinkLogo />
        <Trigger>
          <IconButton aria-label="Open navigation menu">
            <StyledHamburger />
          </IconButton>
        </Trigger>
        <Target placement={"right"} preventScroll>
          <MobileMenu />
        </Target>
      </Nav>
    </Drawer>
```

**Comment by jaredLunde** [comment]
I don't think it's supposed to loop back? This is just a drawer not something like https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-actions-active-descendant.html
